apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-ui-blue
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-ui
      slot: blue
  template:
    metadata:
      labels:
        app: heart-ui
        slot: blue
    spec:
      containers:
        - name: heart-ui
          image: asia-south1-docker.pkg.dev/heart-mlops-2026/heart-app/heart-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: HEART_API_URL
              value: "http://heart-api-svc.prod.svc.cluster.local:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-ui-green
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-ui
      slot: green
  template:
    metadata:
      labels:
        app: heart-ui
        slot: green
    spec:
      containers:
        - name: heart-ui
          image: asia-south1-docker.pkg.dev/heart-mlops-2026/heart-app/heart-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: HEART_API_URL
              value: "http://heart-api-svc.prod.svc.cluster.local:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: heart-ui-svc
  namespace: prod
spec:
  selector:
    app: heart-ui
    slot: blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
